import { moreGuides } from "./more-guides";

export type Guide = {
  date?: string;
  updated?: string;
  slug: string; title: string; description: string; category: string;
  dimensions: [string, string, string][];
  intro: string; steps: string[];
  sections: { title: string; paragraphs: string[] }[];
  tool: string; toolLabel: string;
  sources: { label: string; url: string }[];
};

export const published = "2026-09-05";
export const guides: Guide[] = [
  ...moreGuides,
  {
    slug: "instagram-post-image-size", updated: "2026-09-18", category: "Social media",
    title: "How to resize a photo for an Instagram post",
    description: "Prepare square and portrait Instagram images, choose JPG or PNG, and avoid stretching photos when changing aspect ratio.",
    intro: "Start with the shape of the post, then choose the pixel dimensions. A portrait photograph and a square product card need different compositions, even when both are 1080 pixels wide. This tutorial uses practical export canvases; preview your post in the app or scheduler you actually use before publishing.",
    dimensions: [["Square canvas", "1080 × 1080 px", "1:1"], ["Portrait canvas", "1080 × 1350 px", "4:5"], ["Taller portrait canvas", "1080 × 1440 px", "3:4"]],
    steps: ["Choose the original photograph, not a screenshot of a previous Instagram upload. Repeated saving can introduce visible artifacts.", "Choose a square or portrait composition. Use ResizeFox’s Crop Image tool to prepare the composition first. Set crop width and height to the desired ratio, then position the crop around the subject.", "Open the image resizer, select your cropped image and keep Maintain aspect ratio enabled. Enter a width of 1080 pixels and check the resulting height.", "Choose JPG for a photograph or PNG for a graphic when sharp edges matter. Resize and inspect the result before downloading.", "Upload to Instagram and inspect both the post and its profile preview. For a carousel, prepare a consistent canvas and review every slide for unwanted cropping."],
    sections: [
      { title: "Worked example: from a phone photo to a portrait post", paragraphs: ["A 3024 × 4032 photograph has a 3:4 ratio. Reducing its width to 1080 gives a height of 1440: 4032 × 1080 ÷ 3024 = 1440. No stretching is needed. To make a 4:5 composition, crop the source to 3024 × 3780 first, then resize to 1080 × 1350.", "The crop removes 252 pixels of height in this example. Decide which part of the background can go rather than letting an automatic center crop cut into a face or product. These numbers are a geometry example, not a measured compression result."] },
      { title: "Why the post and profile thumbnail may look different", paragraphs: ["A platform can show one image inside several containers. Keep a title and the main subject away from the outer edges, and use the final app preview to judge placement. Do not assume that a full-size export guarantees the same framing in the grid.", "Publishing tools can support different combinations of ratios. The dimensions above are preparation options, not a promise that every placement or scheduler accepts each one. If a taller image is cropped in your workflow, prepare a deliberate 4:5 or square version instead."] },
      { title: "Do you need to compress it to 100 KB?", paragraphs: ["A pixel target is not a file-size requirement. Do not apply a very small KB limit unless the receiving workflow actually asks for it. Fine text and textures can suffer unnecessarily. Compare your exported image at normal phone display size and keep the original so you can try another export."] },
    ], tool: "/resize-image", toolLabel: "Resize your Instagram image",
    sources: [{ label: "Instagram Help: photo resolution (may require sign-in; check your publishing workflow)", url: "https://help.instagram.com/1631821640426723" }],
  },
  {
    slug: "facebook-reels-dimensions", category: "Social media",
    title: "Facebook Reels: prepare vertical images and cover artwork",
    description: "Use a 9:16 canvas for vertical Reel artwork, understand 1080 × 1920, and keep important content away from interface overlays.",
    intro: "A Reel is a video, but it may contain still photographs, title cards and cover artwork. Prepare those assets for the composition of your video before you edit. A 1080 × 1920 canvas is a practical full-height 9:16 working size; it is not a claim that Facebook requires every Reel to use that exact resolution.",
    dimensions: [["Vertical artwork", "1080 × 1920 px", "9:16"], ["Smaller vertical canvas", "720 × 1280 px", "9:16"], ["Landscape source example", "1920 × 1080 px", "16:9"]],
    steps: ["Create a vertical project in your video editor and decide whether each source photo should fill the frame or fit inside it.", "If the photo should fill the frame, crop to 9:16 in an editor first. If the entire image matters, place it on a vertical canvas with deliberate margins instead.", "Use ResizeFox to resize the prepared still image to 1080 × 1920 with its aspect ratio locked. Keep a PNG for artwork that needs transparency in the editor.", "Import the image into your video editor. Add motion, captions and audio there; ResizeFox does not export MP4 files or resize videos.", "Preview the Reel on Facebook. Check the cover selection, interface overlays and any cropped thumbnail before publishing."],
    sections: [
      { title: "Fit versus fill: a large difference for landscape photos", paragraphs: ["A 1920 × 1080 landscape image cannot become a full-height portrait without a composition decision. Fitting it into a 1080-pixel-wide vertical canvas produces an image about 608 pixels high, leaving substantial space above and below. Filling that canvas instead crops much of the left and right sides.", "Neither choice is automatically wrong. For a group photo, fitting may preserve everyone. For a product close-up, a tighter crop may work. Stretching the landscape image to 1080 × 1920 distorts the subject and is usually the least useful option."] },
      { title: "Use preview-based margins", paragraphs: ["Keep essential titles and faces toward the central portion of your design. Interface buttons and captions can cover parts of the video, and their position can change. There is no universal margin in this guide: inspect the actual placement in the publishing preview.", "If you are making an advertisement, use the current placement-specific specifications in Meta Ads Manager. Advertising specifications should not be treated as universal limits for ordinary posts."] },
      { title: "Image extensions are not video settings", paragraphs: ["JPG and PNG describe your still asset. They do not specify video frame rate, codec or bitrate. Export the finished timeline using your video editor and the current Facebook upload requirements. Renaming an image from .jpg to .mp4 does not create a video."] },
    ], tool: "/resize-image", toolLabel: "Prepare a still image for your Reel",
    sources: [{ label: "Meta: Facebook video publishing changes", url: "https://about.fb.com/news/2025/06/making-it-easier-create-videos-facebook/" }, { label: "Meta: Facebook and Instagram Reels advertising", url: "https://www.facebook.com/business/ads/facebook-instagram-reels-ads" }],
  },
  {
    slug: "tiktok-resolution-image-guide", category: "Social media",
    title: "TikTok resolution: prepare a 9:16 image for your video",
    description: "Understand 1080 × 1920 versus 720 × 1280, prepare vertical still assets and avoid confusing image compression with video export.",
    intro: "For a vertical TikTok project, 1080 × 1920 gives you a 9:16 canvas. Use it as a practical editing choice for still artwork, not as a universal upload limit. TikTok's advertising guidance recommends vertical 9:16 creative, at least 720P footage and attention to interface safe zones. Organic posts and ad placements should be checked separately.",
    dimensions: [["Full-HD portrait working canvas", "1080 × 1920 px", "9:16"], ["720P portrait working canvas", "720 × 1280 px", "9:16"], ["Same ratio, larger source", "2160 × 3840 px", "9:16"]],
    steps: ["Check the source dimensions. A 2160 × 3840 portrait image can scale down directly; a square image needs a crop or a background canvas first.", "Prepare the composition in your image editor. Keep important text away from the lower caption area and the side occupied by controls, then verify in TikTok rather than assuming a fixed safe-zone template.", "Open ResizeFox's pixel resizer, keep Maintain aspect ratio enabled and set the width to 1080. A 9:16 source should give a height of 1920.", "Download JPG for a photo or PNG when you need transparency for compositing. Import the still asset into your video editing project.", "Export the actual video in your editor. Upload a preview to the intended TikTok workflow and check text readability, framing and audio before publishing."],
    sections: [
      { title: "Why doubling pixels does not guarantee more detail", paragraphs: ["A 720 × 1280 image contains 921,600 pixels. A 1080 × 1920 canvas contains 2,073,600. Enlarging the smaller source adds interpolated pixels, but it does not reconstruct a missing logo edge or an unreadable label. Start with the original artwork whenever possible.", "If your source is already small, compare the native version with the enlarged version at the actual viewing size. A clean, modest-resolution source can be preferable to an oversized file with visible softness."] },
      { title: "Do not use a passport-size compression target for video artwork", paragraphs: ["A 20 KB target is designed for restrictive image uploads. It can be far too aggressive for a full-height title card with text and gradients. Set pixel dimensions first and only apply a file-size limit when a specific image upload step asks for it.", "A video's file size depends on duration, audio and encoding as well as resolution. Compressing one still image does not set the finished video's size. ResizeFox currently processes still JPG, PNG and WebP images, not video streams."] },
      { title: "Check each destination independently", paragraphs: ["Reusing an asset across TikTok and Reels saves design time, but each app can show different controls and thumbnail crops. Keep an editable original so you can move text for a second placement without stretching or repeatedly recompressing the exported image."] },
    ], tool: "/resize-image", toolLabel: "Resize a TikTok still asset",
    sources: [{ label: "TikTok for Business: creative best practices for performance ads", url: "https://ads.tiktok.com/resources/help/article/creative-best-practices" }],
  },
  {
    slug: "passport-photo-dimensions-pixels", category: "Documents",
    title: "Passport photo dimensions: millimetres, pixels and country rules",
    description: "Understand French 35 × 45 mm and US 2 × 2 inch photo formats, pixel calculations, and why resizing cannot certify an identity photo.",
    intro: "There is no single worldwide passport-photo resolution. First identify the country and whether you are submitting a printed photograph or using an online application. The physical dimensions of a print, the pixel dimensions of a file and the permitted file size are three separate requirements.",
    dimensions: [["France: printed photo", "35 × 45 mm", "7:9"], ["United States: printed photo", "2 × 2 inches", "1:1"], ["35 × 45 mm at 300 PPI, rounded example", "413 × 531 px", "Print calculation only"]],
    steps: ["Open the issuing authority's instructions for your application. Do not use a social-media size chart or another country's passport requirements.", "Obtain an appropriate source photo. France requires a qualified professional or approved booth; a resized casual photograph is not a substitute.", "Separate the rules for physical size, face position, background and expression from any digital upload requirements.", "If your application permits you to resize a digital file, use an already correctly composed photo and keep its proportions locked. Avoid filters, face retouching and background replacement.", "Check the finished file against the issuing authority's instructions. For printing, verify the final measured size and disable automatic fit-to-page scaling in the print workflow."],
    sections: [
      { title: "Two countries, different requirements", paragraphs: ["France specifies a 35 × 45 mm photograph and a face height between 32 and 36 mm. The background must be plain and light, but white is prohibited. The US printed format is 2 × 2 inches with a white or off-white background. These examples show why a generic passport preset cannot establish compliance.", "Both examples are summaries of the linked authority pages. Read the complete instructions for your own application, including photograph age, pose, accessories and submission method. ResizeFox does not perform biometric checks or certify acceptance."] },
      { title: "How to calculate pixels from millimetres", paragraphs: ["Use pixels = millimetres ÷ 25.4 × pixels per inch. At a chosen 300 PPI, 35 mm corresponds to about 413 pixels and 45 mm to about 531 pixels. This is a mathematical print example, not an official digital-upload specification. Rounding can produce a tiny difference in ratio.", "Changing a file's pixel dimensions does not necessarily set its print density metadata. A print application can still place it at the wrong size. Measure a test print, or use the approved photographer's supplied print rather than assuming an on-screen ruler is accurate."] },
      { title: "A smaller file can still be unacceptable", paragraphs: ["Meeting a 100 KB upload limit does not prove that a face is the correct height, the background is allowed or the photo is recent. Excessive compression can damage the edges around eyes and hair. If an official portal specifies pixels and bytes, both conditions must hold at the same time.", "The size-target tools can reduce dimensions and convert an oversized PNG to JPG with white background. That makes them inappropriate as an automatic identity-photo compliance step, particularly when white is not allowed. Work from the authority's instructions and retain the approved original."] },
    ], tool: "/resize-image", toolLabel: "Resize a permitted digital copy",
    sources: [{ label: "France: Service Public identity-photo requirements", url: "https://www.service-public.gouv.fr/particuliers/vosdroits/F10619" }, { label: "United States: Department of State passport photos", url: "https://travel.state.gov/en/passports/apply/help/photos.html" }],
  },
  {
    slug: "jpg-png-webp-file-extensions", category: "File formats",
    title: "JPG, PNG or WebP: which image extension should you choose?",
    description: "Choose a format for photos, transparent logos and web images, and learn why renaming a file does not convert it.",
    intro: "Choose the file format from the job the image has to do. A photograph for a form, a transparent logo and a website illustration have different needs. The smallest result is only useful if the destination can open it and the visible detail remains suitable.",
    dimensions: [["JPG / JPEG", "Photographs and broad compatibility", "No transparency"], ["PNG", "Transparent graphics and sharp artwork", "Often heavier for photos"], ["WebP", "Web images when supported", "Supports transparency"]],
    steps: ["Check which extensions the receiving website accepts. If it specifically asks for JPG, do not send WebP even if that file is smaller.", "Keep the original file. Open it in the ResizeFox tool on the home page and select Convert after choosing your image.", "Choose the output format. For a transparent logo, use PNG or WebP; choose JPG only when a solid background is appropriate.", "For JPG or WebP, adjust quality and convert. Inspect small text, smooth gradients and subject edges rather than judging only by the file-size number.", "Download and check the extension. Open the downloaded file once before uploading it to the destination."],
    sections: [
      { title: "JPG and JPEG are the same format", paragraphs: ["The .jpg and .jpeg extensions both refer to JPEG images. A form may still implement a narrow extension check, so follow its instructions. Renaming .png to .jpg changes the filename, not the underlying encoding; an actual conversion is needed.", "JPEG is useful for many photographs, but it cannot represent transparent pixels. In ResizeFox, conversion to JPG paints those areas white. That is useful for a photo on a white canvas and unsuitable for a logo that must blend into a dark header."] },
      { title: "Why a tiny PNG can become a bigger JPG", paragraphs: ["Flat graphics can encode efficiently in PNG. Converting them to a photographic format does not guarantee a smaller file. In our local browser check, an 800 × 600 transparent striped test image was 5.59 KB as PNG, while one JPG result targeting 20 KB was 19.86 KB. This is a single synthetic example; other images and browsers produce different results.", "The dedicated size-limit tools now preserve a supported original file when it is already within the limit. For that same test image, the result remained PNG at 5.59 KB. If you deliberately need another format, use Convert instead of expecting the size tool to force a conversion."] },
      { title: "Transparency and visible quality need separate checks", paragraphs: ["A white preview background can make a transparent and an opaque image look similar. Test a logo against the intended page background in your design workflow. For text artwork, examine thin strokes at normal display size and avoid exporting repeatedly from already compressed copies.", "WebP can be useful when a web workflow supports it, but a document portal may reject it. File-size efficiency does not override format compatibility. Keep a source copy so you can create a different export without losing another generation of detail."] },
    ], tool: "/", toolLabel: "Open the image converter",
    sources: [{ label: "MDN: image file types and formats", url: "https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Image_types" }],
  },
  {
    slug: "compress-image-upload-limit", category: "File size",
    title: "How to meet a 20 KB, 100 KB or 1 MB image upload limit",
    description: "A step-by-step workflow for meeting file-size limits while checking dimensions, output format and legibility.",
    intro: "When an upload form rejects a file, copy down the exact requirements before changing anything: accepted format, maximum bytes and any required pixel dimensions. A successful upload needs all of them. This tutorial helps you choose a size target without treating compression as a guarantee of acceptance.",
    dimensions: [["Small limit", "20–50 KB", "Expect stronger compromises"], ["Medium limit", "100–250 KB", "Inspect faces and text"], ["Larger limit", "500 KB–1 MB", "More room, not a quality guarantee"]],
    steps: ["Read the destination's error message and confirm the required extension and dimensions. Keep an untouched original.", "If the image is much larger in pixels than necessary, open the pixel resizer first. Reduce width with Maintain aspect ratio enabled and download that copy.", "Open the matching size-limit tool. Select the prepared file, then run compression. A file already below the limit will be preserved.", "Read the actual result size and output format. Oversized PNG files may become JPG with a white background; WebP remains WebP.", "Inspect the preview and the downloaded image. Confirm the pixel dimensions still satisfy the destination before submitting it."],
    sections: [
      { title: "Why the result may be below, rather than exactly at, the target", paragraphs: ["The compressor searches quality settings and can reduce pixel dimensions if needed. It aims to fit below a ceiling, not add padding to manufacture an exact file size. A 97 KB result can satisfy a 100 KB maximum just as well as a 99 KB result.", "File complexity matters: detailed foliage, noise and fine text can be harder to compress than a plain background. Do not expect the same visual quality for two unrelated images simply because the resulting files have the same size."] },
      { title: "KB versus bytes: check a strict portal carefully", paragraphs: ["ResizeFox uses 1 KB = 1,024 bytes, and its 1 MB preset uses 1,024 KB. A portal that means 100,000 bytes by 100 KB is stricter than a tool target of 102,400 bytes. For that decimal 100 KB example, a custom target of 97 KB means 99,328 bytes and leaves a small margin.", "On the general compressor, read the result message: if the target cannot be met, the available download may still be above the limit. Choose another format or reduce dimensions and try again. Do not interpret the presence of a download button as proof that the file meets your portal's rules."] },
      { title: "Troubleshoot without ruining the original", paragraphs: ["If text becomes unreadable, start again from the original and crop irrelevant background in an image editor before resizing. If the destination specifies minimum dimensions, do not keep shrinking blindly. A larger allowed target or a cleaner source may be the only suitable solution.", "If the file is accepted locally but rejected on upload, inspect its real extension, actual bytes and pixel dimensions. The portal may also enforce content rules that a size tool cannot evaluate. For identity photos, consult the country-specific instructions before making any edits."] },
    ], tool: "/compress-image", toolLabel: "Choose a compression target", sources: [],
  },
  {
    slug: "resize-crop-aspect-ratio", category: "Dimensions",
    title: "Resize or crop? Change image dimensions without stretching",
    description: "Use aspect ratios and worked pixel calculations to decide when to resize, crop or add a canvas around an image.",
    intro: "Resizing changes the number of pixels. Cropping removes part of the composition. Adding a canvas preserves the whole picture with space around it. Choose between these operations before entering a width and height, especially when moving from a landscape photo to a square post or vertical Reel.",
    dimensions: [["Landscape example", "1200 × 800 px", "3:2"], ["Proportional reduction", "600 × 400 px", "3:2"], ["Square composition", "800 × 800 px", "1:1"]],
    steps: ["Find the original width and height. Divide width by height to understand its shape; 1200 ÷ 800 = 1.5, or 3:2.", "Compare that ratio with your destination. If they match, resize directly with Maintain aspect ratio enabled.", "If the ratios differ, crop in an editor or place the entire photo on a canvas matching the destination. ResizeFox does not currently crop or add layout margins for you.", "Upload the prepared image to the resizer. Enter one dimension and check that the other updates to the expected value.", "Preview the result, download it and check that faces and round objects keep their original proportions."],
    sections: [
      { title: "Worked example: a square product card", paragraphs: ["To turn a 1200 × 800 photo into a square by cropping, retain an 800 × 800 region and remove 400 pixels of total width. A centered crop would remove 200 from each side, but the subject may need an off-center crop. After that, resizing to 600 × 600 preserves the square shape.", "If no part of the photo can be removed, fit it inside a square canvas instead. At 600 pixels wide, the full photograph becomes 600 × 400, leaving 200 pixels of vertical space in a 600 × 600 canvas. A layout editor can divide that into 100 pixels above and below."] },
      { title: "What happens when you unlock the ratio", paragraphs: ["Entering 600 × 600 directly for a 1200 × 800 source applies different horizontal and vertical scale factors. A circle becomes an oval and a product changes apparent shape. The tool can do this, but it is not a substitute for deciding which area to crop.", "Keep the ratio locked for portraits, products and identity documents. Unlocking it is mainly useful when distortion is intentional. If exact dimensions and undistorted content are both required, prepare the matching crop or canvas first."] },
      { title: "Pixel dimensions do not determine file size", paragraphs: ["Two 600 × 600 images can have very different file sizes because of their content and encoding. Set the composition and dimensions first, then address any byte limit separately. A file-size tool may reduce dimensions further, so recheck both requirements after compression.", "Also remember that upscaling cannot recover detail that was absent in the source. Keep your high-resolution original and export new copies for each destination instead of repeatedly resizing the same small download."] },
    ], tool: "/resize-image", toolLabel: "Resize while preserving proportions", sources: [],
  },
];
