import type { Guide } from "./articles";

export const moreGuides: Guide[] = [
  {
    slug: "resize-screenshot-keep-text-readable", category: "Documents", date: "2026-09-07",
    title: "How to resize a screenshot without making the text unreadable",
    description: "Prepare readable screenshots for support tickets and tutorials by cropping first, preserving text detail and checking the exported copy.",
    intro: "A screenshot is useful only if its reader can identify the problem. Compressing an entire desktop into a small attachment often makes the relevant message too tiny to read. Start by deciding what the recipient actually needs to see, then reduce the image around that information.",
    dimensions: [["Full desktop example", "2560 × 1440 px", "Often includes unnecessary space"], ["Relevant crop example", "1200 × 800 px", "Crop in an image editor first"], ["Half-size crop", "600 × 400 px", "Text also becomes half as tall"]],
    steps: ["Capture the error and enough surrounding interface to explain where it happened. Keep an untouched copy for reference.", "Use a screenshot or image editor to crop unrelated windows and redact private information with an opaque mark. ResizeFox does not provide cropping or redaction.", "Open the cropped file in the pixel resizer. Keep Maintain aspect ratio enabled and choose PNG output as a starting point for text-heavy content.", "Try one reduction, download the result and open it at normal viewing size. Read the smallest important text, including error codes and punctuation.", "If a support portal imposes a byte limit, compress only after checking readability. If the text becomes unclear, split the evidence into a contextual screenshot and a close-up when the portal permits multiple files."],
    sections: [
      {title: "Worked example: why cropping helps more than shrinking", paragraphs: ["Suppose the error panel occupies 1200 × 800 pixels inside a 2560 × 1440 desktop capture. Reducing the whole desktop to 640 pixels wide scales everything to one quarter of its original size. A 16-pixel-high character becomes roughly 4 pixels high, which is insufficient for reliable reading.", "Cropping the panel first and keeping it 1200 pixels wide retains the original character size while removing irrelevant pixels. The result may still need compression, but you have not sacrificed text detail just to include empty desktop space. This example is a scale calculation, not a measured file-size saving."]},
      {title: "Inspect the characters that carry the meaning", paragraphs: ["Check similar characters such as 0 and O, 1 and l, and punctuation in a URL or error code. A screenshot can look clean at a glance while losing the distinction that makes it useful. If the page allows text, paste the error message as text alongside the image.", "JPG can introduce fringes around sharp text. PNG is a useful starting point, but it does not undo damage already present in a low-quality source. Re-capture the application if possible rather than converting a blurred JPG back to PNG and expecting the missing detail to return."]},
      {title: "Check the attachment, not just the editor preview", paragraphs: ["Open the downloaded copy and view it at the size the recipient is likely to use. Confirm the right region was captured and the private details are no longer visible. Do not rely on a small email preview to confirm that a full-resolution attachment is unreadable; inspect the actual file."]},
    ], tool: "/resize-image", toolLabel: "Resize a screenshot", sources: [{label: "MDN: choosing image formats",url: "https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Image_types"}],
  },
  {
    slug: "resize-transparent-logo-png", category: "File formats", date: "2026-09-07",
    title: "Resize a transparent PNG logo without adding a white background",
    description: "Keep transparency, check logo edges on light and dark backgrounds and distinguish a transparent file from a white-background image.",
    intro: "A logo can look correct on a white preview and still display an unwanted rectangle on a dark website. To avoid that surprise, preserve both the transparent pixels and the proportions of the artwork. This workflow starts with an existing transparent PNG; it does not remove the background from a photograph.",
    dimensions: [["Wide logo example", "1200 × 300 px", "4:1"], ["Smaller wide copy", "400 × 100 px", "Same proportions"], ["For a 200 × 50 display example", "400 × 100 px source", "A 2× preparation option"]],
    steps: ["Find the original transparent PNG. If you only have a JPG on a white background, obtain a transparent export from the original design rather than merely renaming the file.", "Open ResizeFox's pixel resizer and keep Maintain aspect ratio enabled. Enter the width needed by the destination and inspect the calculated height.", "Choose PNG output. Avoid JPG when transparent areas must remain transparent, because JPG cannot store them.", "Download the resized copy. Place it against both a light and a dark background in your design or website preview.", "Check for a white rectangle, pale edge halo, stretched lettering and excessive empty margins before replacing the existing logo."],
    sections: [
      {title: "A checkerboard is a preview convention", paragraphs: ["Some editors show transparent areas as a checkerboard; others show them on white. The appearance of the preview alone does not tell you whether the exported file contains transparency. A screenshot of a checkerboard logo may even include the checkerboard as real pixels.", "Use the actual PNG download in a layout with a colored background to check the result. A pale outline can be part of the original artwork, especially if it was prepared for a white surface. Preserving transparency will not automatically remove those edge colors."]},
      {title: "Keep the logo shape, including its canvas", paragraphs: ["For a 1200 × 300 logo, entering 400 pixels wide should give 100 pixels high. Entering 400 × 400 instead stretches the lettering. If a platform requires a square avatar, place the logo on a square canvas in a design editor rather than stretching it to fill the square.", "Large transparent margins can make a logo appear tiny even when its pixel dimensions seem adequate. Crop those margins in an editor if the layout allows it, then resize the new canvas. ResizeFox currently changes dimensions but does not trim empty borders automatically."]},
      {title: "Do not force a logo through a photo-size preset", paragraphs: ["The dedicated KB-limit tools may convert an oversized PNG to JPG to reach the target. For transparent logos, use the pixel resizer with PNG output instead. If the destination supports WebP, you can evaluate a transparent WebP copy, but always inspect fine lettering after conversion.", "Keep the editable design or original vector file for future sizes. ResizeFox's image uploader supports JPG, PNG and WebP; it is not a vector-logo editor. Enlarging a small raster logo cannot recreate the clean curves of the original design."]},
    ], tool: "/resize-image", toolLabel: "Resize a PNG logo", sources: [{label: "MDN: transparency and image formats",url: "https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Image_types"}],
  },
  {
    slug: "product-photos-consistent-dimensions", category: "Product photos", date: "2026-09-07",
    title: "Prepare consistent product photos for an online shop",
    description: "Create matching product-image canvases, preserve visible detail and avoid confusing equal pixel dimensions with consistent framing.",
    intro: "A product grid can look uneven even when every file is exactly the same width and height. One item may fill its frame while another is surrounded by empty space. Consistency comes from composition first, followed by dimensions and a sensible file-size budget. This guide uses an example shop grid rather than claiming a universal marketplace requirement.",
    dimensions: [["Example square source", "2400 × 2400 px", "Retain as the master"], ["Example shop export", "1200 × 1200 px", "Check your actual platform"], ["Example thumbnail", "400 × 400 px", "Do not use as the zoom master"]],
    steps: ["Read your shop platform's image requirements, including zoom needs and permitted formats. Separate these rules from the size of a small grid thumbnail.", "Choose a consistent composition in your editor: square or portrait canvas, similar margins and a repeatable baseline for the product.", "Export a prepared source for each item. Resize it in ResizeFox with the aspect ratio locked, using the same dimensions for the set.", "Choose JPG for photographs when a solid background is appropriate. Keep PNG for assets that must remain transparent.", "Review the files together in the shop preview. Check small labels and material texture in the zoom view as well as balance in the thumbnail grid."],
    sections: [
      {title: "Worked example: equal canvases, unequal products", paragraphs: ["Imagine two 1200 × 1200 images. A bottle occupies 1000 pixels of height in one, but only 600 pixels in the other. Their file dimensions match, yet the second bottle looks much smaller. Changing both files to 800 × 800 retains that inconsistency.", "Adjust the composition before resizing. You could frame both bottles at a similar fraction of the canvas height while keeping enough margin for the cap and base. The right proportion depends on the objects; this is a layout decision rather than a compression setting."]},
      {title: "Evaluate detail that affects the purchase", paragraphs: ["Inspect stitching, surface texture, labels and small accessories. These details can become softer under aggressive compression even when the broad shape remains clear. Use the original to make a less compressed version if important information is lost.", "Do not invent detail by enlarging a small thumbnail or repeatedly sharpening a damaged copy. If the source does not show the relevant feature, a better photograph is often more useful than another export setting. Keep separate close-ups where your platform allows them."]},
      {title: "Avoid one file-size target for every product", paragraphs: ["A plain ceramic cup and a patterned fabric can compress very differently at the same dimensions. Compare visible quality instead of forcing both to an identical byte count. A larger file may be justified when it preserves information buyers need, within the destination's limits.", "Prepare web copies from the same original rather than downloading the shop's already processed thumbnail as the source for your next edit. Name the files clearly by product and view so that a front image is not accidentally replaced with a detail crop."]},
    ], tool: "/resize-image", toolLabel: "Resize a product photo", sources: [],
  },
  {
    slug: "email-several-photos-attachment-size", category: "File size", date: "2026-09-07",
    title: "How to prepare several photos for one email",
    description: "Budget attachment sizes across a set of photos, preserve useful detail and choose between attached files and a shared original.",
    intro: "An email with several photographs needs a budget for the whole set, not just one image. Start with what the recipient needs: a quick visual reference, readable documentation or full-resolution files for editing. Those goals call for different copies of the same source photographs.",
    dimensions: [["Example: 8 photos at 500 KB", "4,000 KB combined", "Before message overhead"], ["Example: 8 photos at 1,024 KB", "8,192 KB combined", "Twice the budget or more"], ["Full-resolution originals", "Use actual file sizes", "Consider a shared folder"]],
    steps: ["Check your email service and recipient's attachment limits. Gmail currently describes a 25 MB total attachment limit for personal accounts; workplace rules and receiving systems may differ.", "Decide which images are necessary and remove duplicates from the set you plan to send. Keep the originals separately.", "For viewing copies, resize oversized images to the dimensions appropriate for the recipient's task, with proportions locked.", "Compress one photo, inspect the result and use that as a starting point for the others. ResizeFox processes one image at a time; it does not batch-export an email package.", "Add up the actual exported file sizes, attach the files and review the message. If the originals are needed, use a sharing workflow with appropriate access instead of degrading them to fit an attachment budget."],
    sections: [
      {title: "Worked budget: eight photos", paragraphs: ["If each of eight exported files is at most 500 KB in ResizeFox, their combined budget is 4,000 KB, or approximately 3.91 MiB using 1,024-based units. This is an upper-bound calculation, not a prediction that every photo will finish at exactly 500 KB.", "The transmitted message can be larger than the raw files because attachments must be encoded for email. Leave room for that overhead and for any other attachments. Do not plan a set that sits exactly on a stated maximum and assume it will pass every receiving system."]},
      {title: "Match quality to the recipient's task", paragraphs: ["For choosing between room layouts, a moderate-size photo may be enough. For inspecting a serial number or a fabric defect, preserve that detail and include a close-up. For printing or professional editing, ask for the required source format and resolution rather than assuming an email-sized JPG is sufficient.", "Open the exported file at a normal viewing scale and read any important labels. If reducing the whole image makes the label unreadable, send a separate detail image when practical. Re-export from the original rather than compressing the already compressed copy again."]},
      {title: "When the attachment turns into a link", paragraphs: ["Gmail's documented behavior for files beyond its attachment limit is to use a Google Drive link. That changes the delivery method: the recipient may need permission to open the shared content. Check access in the sharing service, especially when communicating outside your organization.", "A sent email does not prove that a recipient could access every linked file. Keep the original set until delivery is confirmed, and use clear filenames so the recipient can distinguish views without opening every attachment."]},
    ], tool: "/compress-image-for-email", toolLabel: "Prepare an email photo", sources: [{label: "Gmail Help: attachment size and Drive links",url: "https://support.google.com/mail/answer/6584?hl=en"}],
  },
  {
    slug: "website-image-size-display-width", category: "Website images", date: "2026-09-07",
    title: "Choose image dimensions for a website without guessing",
    description: "Start from the displayed image width, prepare useful variants and measure actual file size rather than relying on a universal KB rule.",
    intro: "A large banner, a product thumbnail and an inline screenshot do not need the same export. Before compressing, find out how wide the image is displayed in your page layout and what detail visitors need. This guide describes preparation choices; a website's implementation determines which version is actually delivered.",
    dimensions: [["Example content column", "800 CSS pixels wide", "Layout measurement"], ["Example 1× source", "800 image pixels wide", "Baseline candidate"], ["Example 2× source", "1600 image pixels wide", "Compare quality and weight"]],
    steps: ["Inspect the intended page on a phone and a larger screen. Find the largest width at which this image is meant to appear, not the width of the entire monitor.", "Decide the crop or canvas shape in your image editor. Keep faces, labels and the meaningful part of the picture inside the composition.", "Use ResizeFox to prepare an appropriately sized copy with its aspect ratio locked. Keep the full-resolution original outside this export workflow.", "Compare JPG and WebP for a photograph if your publishing system supports both. Use PNG when transparent or text-heavy artwork requires it.", "Upload the candidate and inspect the real page. Check loading, sharpness and cropping on more than one screen; verify that your site serves the intended file rather than an old oversized original."],
    sections: [
      {title: "Worked example: an 800-pixel article column", paragraphs: ["For a source photo measuring 3000 × 2000, reducing width to 800 produces roughly 800 × 533 pixels. A 1600-pixel-wide version is roughly 1600 × 1067. The second candidate has about four times the pixel count, although its compressed byte size will not necessarily be four times as large.", "Compare both in the actual page. A higher-density display may benefit from the larger candidate, while a small thumbnail may not justify it. Preparing several sizes is useful only if the publishing system chooses between them; putting all versions in a folder does not automatically make the page responsive."]},
      {title: "An image budget is a decision, not a universal rule", paragraphs: ["A simple flat illustration and a detailed photograph can need different byte budgets. Begin with acceptable visible quality, measure the downloaded file size and reduce unnecessary dimensions before forcing extreme compression. There is no single 100 KB rule that makes every website image correct.", "Use a real page preview to inspect small text, smooth gradients and edges. A file that looks acceptable inside the resizer can become soft if the page enlarges it beyond its prepared dimensions. Fix the mismatch between the layout and source rather than repeatedly lowering image quality."]},
      {title: "What resizing does not solve", paragraphs: ["ResizeFox prepares image files; it does not change your site's responsive image markup, caching, image-loading order or alternative text. Those concerns belong to your website editor or implementation. Smaller exports can help reduce transferred bytes, but they do not guarantee a particular speed score.", "Provide meaningful alternative text in the destination page when the image conveys information. Avoid placing essential instructions only inside a picture: normal page text remains readable when images fail to load and is easier for visitors to copy or translate."]},
    ], tool: "/resize-image", toolLabel: "Prepare a website image", sources: [],
  },
];
