import type { ToolGuide } from "./ToolGuidePage";

const basics = {
  steps: [["Choose an image", "Select a JPG, PNG or WebP file from your device. The file stays in your browser."], ["Set the options", "Choose the values required for the destination where you will use the image."], ["Process and download", "Check the result, then download the new copy to your device."]] as [string, string][],
  faqs: [["Are images uploaded to a server?", "No. ResizeFox uses browser image and canvas features to process the selected file locally."], ["Will the original file be changed?", "No. The downloaded result is a new file; your original remains untouched."], ["Which formats can I use?", "The tool accepts JPG, PNG and WebP. Some operations export JPG or PNG depending on the selected page."]] as [string, string][],
};

export const cropGuide: ToolGuide = { eyebrow: "FREE ONLINE IMAGE CROPPER", title: "Crop an Image Online", intro: "Remove unwanted edges and keep the part of a photo that matters. Enter an exact crop area in pixels and download the result without sending the image to a server.", steps: basics.steps, uses: [["Better composition", "Remove empty space or distractions so the main subject is easier to see."], ["Match a layout", "Create a tighter image before resizing it for a card, profile, listing or document."], ["Remove borders", "Cut away scanner margins, screenshots controls or unwanted frames."], ["Prepare thumbnails", "Choose the meaningful area before making a small thumbnail."]], notes: [{ title: "Cropping changes the frame", paragraphs: ["A crop removes pixels from the outer area of an image. The X value moves the crop from the left edge and Y moves it down from the top. Width and height control the size of the area that remains.", "Crop before resizing when the source and destination have different shapes. This preserves the subject instead of stretching the entire image into a new aspect ratio."] }], faqs: basics.faqs, related: [{href:"/resize-image",title:"Resize image",description:"Change the pixel dimensions after choosing the frame."},{href:"/rotate-image",title:"Rotate image",description:"Correct sideways and upside-down photos."},{href:"/compress-image",title:"Compress image",description:"Reduce the downloaded file size."}] };

export const rotateGuide: ToolGuide = { eyebrow: "FREE ORIENTATION TOOL", title: "Rotate an Image Online", intro: "Turn a JPG, PNG or WebP image 90, 180 or 270 degrees. Preview the new orientation and download a corrected copy privately in your browser.", steps: basics.steps, uses: [["Phone photos", "Correct a photo that displays sideways after transfer or upload."], ["Scanned documents", "Turn portrait and landscape scans into the readable orientation."], ["Product images", "Align listing photos consistently before resizing the set."], ["Creative layouts", "Rotate graphics for posters, stories and presentation designs."]], notes: [{title:"What happens to width and height?",paragraphs:["A 90° or 270° rotation swaps the canvas width and height. A 1200 × 800 image becomes 800 × 1200. A 180° turn keeps the same dimensions.","Rotation changes orientation but does not crop the picture. If the frame also needs tightening, rotate first and then use the crop tool."]}], faqs: basics.faqs, related: [{href:"/flip-image",title:"Flip image",description:"Create a horizontal or vertical mirror."},{href:"/crop-image",title:"Crop image",description:"Remove unwanted edges after rotation."},{href:"/bulk-resize-images",title:"Bulk resize",description:"Give several corrected files one width."}] };

export const flipGuide: ToolGuide = { eyebrow: "FREE IMAGE MIRROR TOOL", title: "Flip an Image Online", intro: "Mirror a picture horizontally or vertically while keeping its original dimensions. The transformation happens locally and the result is ready to download immediately.", steps: basics.steps, uses: [["Mirror a selfie", "Reverse left and right when a front-camera photo appears unfamiliar."], ["Adjust direction", "Make a subject face toward page text or another design element."], ["Correct scans", "Repair an image scanned from the reverse side or with the wrong orientation."], ["Create symmetry", "Generate a mirrored asset for a collage or creative composition."]], notes: [{title:"Horizontal vs vertical flip",paragraphs:["A horizontal flip exchanges the left and right sides, like a mirror. A vertical flip exchanges the top and bottom.","Flipping preserves width, height and the complete frame. Text and logos will also be reversed, so inspect the preview before downloading."]}], faqs: basics.faqs, related: [{href:"/rotate-image",title:"Rotate image",description:"Turn an image by a fixed angle."},{href:"/crop-image",title:"Crop image",description:"Keep only a selected rectangular area."},{href:"/resize-image",title:"Resize image",description:"Set exact width and height values."}] };

export const bulkGuide: ToolGuide = { eyebrow: "MULTIPLE IMAGE RESIZER", title: "Resize Images in Bulk", intro: "Give several JPG, PNG or WebP files the same output width in one operation. Each image keeps its own proportions and can be downloaded separately.", steps: [["Select several files", "Choose a group of supported images from the same folder."], ["Enter one width", "The height of each image is calculated from its original aspect ratio."], ["Resize the batch", "Process the group and download each finished JPG from the results list."]], uses: [["Website galleries", "Prepare a consistent maximum width for article and gallery images."], ["Marketplace photos", "Resize a product set while keeping portrait and landscape proportions."], ["Email collections", "Reduce oversized dimensions before attaching several photos."], ["Team handoffs", "Standardize a folder before sharing it with a designer or editor."]], notes: [{title:"How batch resizing handles different shapes",paragraphs:["Every image receives the chosen width, while its height is calculated independently. A square, portrait and landscape file will therefore keep different heights without becoming distorted.","Batch output uses JPG for broad compatibility. Transparent PNG areas receive the browser canvas default background, so use the single-image PNG resizer when transparency must be preserved."]}], faqs: basics.faqs, related: [{href:"/resize-image",title:"Single image resize",description:"Control both width and height for one file."},{href:"/compress-image",title:"Compress image",description:"Aim for a specific maximum file size."},{href:"/crop-image",title:"Crop image",description:"Adjust the composition before resizing."}] };

export function formatGuide(kind: "resize" | "compress" | "convert", format: string, target?: string): ToolGuide {
  const title = kind === "resize" ? `Resize ${format} Images` : kind === "compress" ? `Compress ${format} Images` : `Convert ${format} to ${target}`;
  const action = kind === "resize" ? "pixel dimensions" : kind === "compress" ? "file size" : "file format";
  const formatUses: Record<string, [string, string][]> = {
    JPG: [["Photographs", "Resize camera and phone photos while keeping a broadly compatible file."], ["Marketplace listings", "Prepare product photographs for grids and zoom views."], ["Email copies", "Create smaller viewing copies while keeping full-resolution originals."], ["Application portals", "Match a stated JPG dimension or file-size limit."]],
    PNG: [["Transparent logos", "Change logo dimensions without replacing transparent pixels with a solid background."], ["Screenshots", "Keep interface text and sharp edges clearer than heavily compressed photographic formats."], ["Icons and diagrams", "Prepare clean graphic assets for a website or document."], ["Design overlays", "Resize artwork that will be placed over another background."]],
    WebP: [["Responsive websites", "Prepare efficient images for modern web pages and content cards."], ["Transparent web graphics", "Keep transparency while using a web-focused format."], ["CMS uploads", "Match the dimensions expected by a publishing system that accepts WebP."], ["Performance testing", "Compare an appropriately sized WebP with an oversized source on the real page."]],
  };
  const steps: [string, string][] = kind === "resize" ? [["Choose the source", `Select a ${format} file and check its original width and height.`], ["Set dimensions", "Enter one dimension with aspect ratio locked, or set both values when the destination requires an exact canvas."], ["Preview and download", `Inspect the proportions and save the resized ${format} copy.`]] : kind === "compress" ? [["Choose the source", `Select the ${format} file whose stored size needs to be reduced.`], ["Set a target", "Enter the required maximum in KB and choose dimensions appropriate for how the image will be viewed."], ["Inspect the result", "Confirm the resulting size and check important details before downloading."]] : [["Choose the source", `Select the ${format} file you need to convert.`], ["Review the destination", `The output is fixed to ${target}; check how transparency and compression differ between the two formats.`], ["Convert and verify", `Download the ${target} copy and open it once before sending it to another service.`]];
  const operationFaq: [string, string] = kind === "resize" ? ["Does resizing improve a small image?", "No. Enlarging creates more pixels but cannot restore detail missing from the source. Begin with the best original available."] : kind === "compress" ? ["Will the result always reach the exact target?", "Not every image can reach a very low limit without major visual or dimensional loss. Inspect the reported output size before uploading it elsewhere."] : ["Is changing the filename extension enough?", "No. Renaming a file does not change its encoding. This tool decodes the source and creates a new file in the destination format."];
  const formatFaq: [string, string] = format === "PNG" ? ["Will transparency remain?", target === "JPG" ? "No. JPG cannot store transparency, so transparent areas are placed on a white background." : "Yes. PNG output retains transparent areas supported by the source and browser canvas."] : format === "WebP" ? ["Does every website accept WebP?", "Many modern browsers and publishing systems do, but a strict form may request JPG or PNG. Follow the destination's accepted-format list."] : format === "JPG" ? ["Are JPG and JPEG different?", "They are two filename extensions for the same JPEG format. A strict form may still specify which extension it expects."] : ["How should I choose an output format?", "Use JPG for many photographs, PNG when transparency or sharp graphic edges matter, and WebP for efficient delivery when the destination supports it."];
  return { eyebrow: `${format} IMAGE TOOL`, title, intro: `Change the ${action} of a ${format} image directly in your browser. Review the options, process a new copy and download it without an account.`, steps, uses: formatUses[format] ?? [["Website images", `Prepare ${format} files for content pages and responsive layouts.`], ["Upload requirements", "Meet a service's documented requirement before submitting."], ["Email and sharing", "Create a practical viewing copy while keeping the original."], ["Design workflow", "Standardize an asset for a larger composition."]], notes: [{title:`Understanding ${format} for this task`,paragraphs:[format === "PNG" ? "PNG preserves transparency and sharp graphic edges. It is useful for logos, interface images and screenshots, but photographs can produce larger files." : format === "WebP" ? "WebP is designed for efficient web delivery and supports both photographic images and transparency. Some older workflows may still ask for JPG or PNG." : "JPG is widely supported and efficient for photographs. It does not preserve transparency, and repeated lossy saves can gradually reduce detail.", kind === "resize" ? "Resizing changes width and height. Keep the aspect ratio enabled to avoid stretching the image." : kind === "compress" ? (format === "PNG" ? "PNG does not use a photographic quality slider. When re-encoding alone is insufficient, ResizeFox gradually reduces pixel dimensions to approach the chosen file-size target while preserving transparency." : "Compression reduces stored data. Compare the result at its intended display size because very low quality can create visible artifacts.") : `Conversion creates a ${target} copy. The source remains unchanged, but format-specific features such as transparency may not carry into the destination.`]}], faqs: [["Are images uploaded to a server?", "No. ResizeFox processes the selected file locally in the browser."], operationFaq, formatFaq], related: [{href:"/tools",title:"All tools",description:"Compare editing, optimization and conversion tools."},{href:"/crop-image",title:"Crop image",description:"Remove unwanted content before export."},{href:"/blog/jpg-png-webp-file-extensions",title:"Format guide",description:"Learn when JPG, PNG and WebP are appropriate."}] };
}
