import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "All Image Tools — Resize, Crop, Compress & Convert", description: "Browse every free ResizeFox image tool for resizing, cropping, rotation, compression, conversion and batch processing.", alternates: { canonical: "/tools" } };

const groups = [
  { title: "Resize", intro: "Change pixel dimensions for one image or a whole set.", tools: [["/resize-image","Image resizer","Set exact width and height."],["/bulk-resize-images","Bulk image resizer","Give several images one output width."],["/resize-jpg","JPG resizer","Resize photographic JPG files."],["/resize-png","PNG resizer","Resize PNG files and preserve transparency."],["/resize-webp","WebP resizer","Change WebP dimensions for the web."]] },
  { title: "Edit", intro: "Change the frame or orientation without installing software.", tools: [["/crop-image","Crop image","Remove edges using an exact pixel area."],["/rotate-image","Rotate image","Turn a photo 90°, 180° or 270°."],["/flip-image","Flip image","Mirror an image horizontally or vertically."]] },
  { title: "Compress", intro: "Reduce file weight for forms, websites and sharing.", tools: [["/compress-image","Image compressor","Choose a target file size."],["/compress-jpg","JPG compressor","Reduce photographic image weight."],["/compress-png","PNG compressor","Optimize a PNG in the browser."],["/compress-webp","WebP compressor","Reduce a WebP file for delivery."],["/compress-image-for-email","Email image compressor","Prepare attachments for email."]] },
  { title: "Convert", intro: "Create a new image copy in a different file format.", tools: [["/convert-image","Image converter","Choose JPG, PNG or WebP output."],["/png-to-jpg","PNG to JPG","Create a compatible JPG copy."],["/jpg-to-png","JPG to PNG","Create a lossless PNG container."],["/webp-to-jpg","WebP to JPG","Prepare WebP for JPG-only systems."]] },
  { title: "PDF", intro: "Create, convert and organize documents privately in your browser.", tools: [["/images-to-pdf","Images to PDF","Combine JPG and PNG files into one PDF."],["/pdf-to-jpg","PDF to JPG","Turn every page into an image."],["/merge-pdf","Merge PDF","Join complete documents in order."],["/split-pdf","Split PDF","Extract pages and page ranges."],["/rotate-pdf","Rotate PDF","Correct the orientation of every page."],["/compress-pdf","Compress PDF","Reduce image-heavy and scanned PDFs."]] },
] as const;

export default function ToolsPage(){return <main className="min-h-screen bg-[#fafafa] text-slate-950"><section className="mx-auto max-w-5xl px-5 pb-10 pt-16 text-center sm:px-8 sm:pt-20"><p className="font-bold uppercase tracking-wider text-orange-600">RESIZEFOX TOOLBOX</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">Free Image Tools</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">Resize, crop, rotate, flip, compress and convert images in your browser. Each tool has its own controls and practical guide, and your files stay on your device.</p></section><section className="mx-auto max-w-6xl px-5 pb-20 sm:px-8">{groups.map(group=><div key={group.title} id={group.title === "PDF" ? "pdf-tools" : undefined} className="mb-14 scroll-mt-24"><h2 className="text-3xl font-black">{group.title}</h2><p className="mt-2 text-slate-600">{group.intro}</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{group.tools.map(([href,title,description])=><Link key={href} href={href} className="group rounded-2xl border border-slate-200 bg-white p-6 transition hover:border-orange-500 hover:shadow-sm"><h3 className="text-lg font-bold group-hover:text-orange-600">{title} →</h3><p className="mt-2 leading-7 text-slate-600">{description}</p></Link>)}</div></div>)}</section><section className="border-t border-slate-200 bg-white"><div className="mx-auto max-w-5xl px-5 py-16 sm:px-8"><h2 className="text-3xl font-black">Need the right dimensions?</h2><p className="mt-4 leading-7 text-slate-600">Our tutorials explain image sizes for Instagram posts, Reels, TikTok, Facebook, YouTube, passports and marketplace listings.</p><Link href="/blog" className="mt-5 inline-block font-bold text-orange-600 underline">Browse practical image guides →</Link></div></section></main>}
