import type { ToolGuide } from "./ToolGuidePage";

type PdfKind = "images-to-pdf" | "pdf-to-jpg" | "merge" | "split" | "rotate" | "compress";
const data: Record<PdfKind, {title:string; intro:string; action:string; detail:string; uses:[string,string][]}> = {
  "images-to-pdf": {title:"Convert Images to PDF",intro:"Combine one or more JPG or PNG images into a single PDF, with one image per page. Arrange files when selecting them and create the document privately in your browser.",action:"Choose one or more images",detail:"Each source image becomes a full PDF page using its original proportions.",uses:[["Scanned paperwork","Combine photographed pages into one document."],["Receipts and records","Store several images in a portable file."],["Portfolio delivery","Package selected designs or photographs."],["Application documents","Turn required image pages into one PDF."]]},
  "pdf-to-jpg": {title:"Convert PDF to JPG",intro:"Turn every page of a PDF into a separate JPG image. Choose the output quality and download only the pages you need.",action:"Choose a PDF",detail:"Every PDF page is rendered as an individual JPG for previews, sharing or image workflows.",uses:[["Page previews","Create thumbnails for a document library."],["Presentation assets","Use a document page as an image."],["Website publishing","Prepare selected pages for an article."],["Easy sharing","Send one visual page instead of a full document."]]},
  merge: {title:"Merge PDF Files",intro:"Combine several PDF documents into one file while keeping their page order. Processing happens on your device without an account.",action:"Choose PDF files",detail:"All pages are copied into one document in the order of the selected files.",uses:[["Monthly records","Join statements or reports into one archive."],["Applications","Combine a form and supporting documents."],["Project handoff","Package separate sections for a recipient."],["Course material","Collect lessons or notes into one file."]]},
  split: {title:"Split and Extract PDF Pages",intro:"Extract selected pages from a PDF or separate every page into its own file. Use simple page numbers and ranges such as 1,3-5.",action:"Choose one PDF",detail:"Enter selected pages or leave the field empty to separate the entire document.",uses:[["Keep one page","Extract a certificate, receipt or form."],["Remove unrelated sections","Share only the relevant page range."],["Separate scans","Turn a combined scan into individual files."],["Reorganize later","Create page files before merging a new order."]]},
  rotate: {title:"Rotate PDF Pages",intro:"Rotate every page in a PDF by 90, 180 or 270 degrees and download a corrected document without uploading it.",action:"Choose one PDF",detail:"The page content and page boxes rotate together while the document order stays unchanged.",uses:[["Correct scans","Fix sideways pages from a scanner."],["Phone documents","Turn photographed paperwork to the readable orientation."],["Landscape reports","Correct pages exported in the wrong direction."],["Print preparation","Align every page before printing."]]},
  compress: {title:"Compress a PDF Online",intro:"Reduce the size of image-based PDFs by rendering pages efficiently and rebuilding the document with adjustable image quality.",action:"Choose one PDF",detail:"This method is best for scans and image-heavy PDFs. It converts page contents to compressed images, so selectable text is not preserved.",uses:[["Scanned documents","Reduce large scanner output."],["Email attachments","Prepare an image-heavy PDF for sending."],["Upload limits","Create a smaller copy for online forms."],["Mobile sharing","Make visual documents easier to transfer."]]},
};

export function pdfGuide(kind: PdfKind): ToolGuide {
  const item=data[kind];
  return {eyebrow:"PRIVATE BROWSER-BASED PDF TOOL",title:item.title,intro:item.intro,steps:[[item.action,"Select the supported files from your device. Nothing is sent to a ResizeFox server."],["Choose the options",item.detail],["Process and download","Review the generated result list and save the new file or page images."]],uses:item.uses,notes:[{title:"How this PDF tool works",paragraphs:[item.detail,"Processing large documents can use significant browser memory. Work with a smaller document or divide it into sections if your device becomes slow."]}],faqs:[["Are my PDF files uploaded?","No. The operation runs locally with browser-based PDF tools."],["Does ResizeFox keep a copy?","No. The generated download exists temporarily in your browser session."],["Can I process a password-protected PDF?","Encrypted files may require removal of the password in an authorized PDF application before this tool can read them."]],related:[{href:"/images-to-pdf",title:"Images to PDF",description:"Combine JPG and PNG files into one document."},{href:"/merge-pdf",title:"Merge PDFs",description:"Join complete PDF documents."},{href:"/split-pdf",title:"Split PDF",description:"Extract individual pages or ranges."}]};
}
