import ImageSizeReference from "../ImageSizeReference";
import type { Metadata } from "next";
import Link from "next/link";
import Lab from "./Lab";

export const metadata: Metadata = { title: "Image Compression Lab: Compare JPG, PNG and WebP", description: "Compare actual image bytes and visible quality using original text, gradient and transparency samples. Run repeatable JPG, PNG and WebP experiments locally.", alternates: { canonical: "/compression-lab" } };

export default function Page() {
  return <main className="bg-[#fafafa] text-slate-950"><article className="mx-auto max-w-6xl px-5 py-12 sm:px-8">
    <p className="font-bold text-orange-700">RESIZEFOX FIELD GUIDE · INTERACTIVE EXPERIMENTS</p>
    <h1 className="mt-4 text-4xl font-black sm:text-5xl">Which image format actually works for your file?</h1>
    <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">A small file is only useful when its details survive. This lab lets you compare the same pixels in PNG, JPG and WebP, with real byte counts and downloadable results. Try our original patterns before experimenting with your photograph or screenshot.</p>
    <p className="mt-4 text-sm text-slate-500">By ResizeFox · Published September 18, 2026</p>
    <Lab />
      <ImageSizeReference />
    <div className="max-w-3xl space-y-10 leading-8 text-slate-700">
      <section><h2 className="text-2xl font-bold text-slate-950">Experiment 1: keep small text readable</h2><p className="mt-4">Select the text pattern, keep the dimensions at 100% and compare at 75% quality. Download the JPG and PNG. View both at 100% zoom and inspect the 12-pixel lettering, the order number and the blue and orange lines. Look for faint halos, blurred punctuation and color bleeding around high-contrast edges.</p><p className="mt-4">Repeat at 25% quality. The test changes encoding while keeping the number of pixels fixed. Then change dimensions to 50%: a 12-pixel character now occupies roughly 6 pixels in height. Even lossless PNG cannot restore detail removed by resizing. For support screenshots, crop unnecessary surroundings before shrinking important text.</p><Link className="text-orange-700 underline" href="/blog/resize-screenshot-keep-text-readable">Read the screenshot preparation walkthrough</Link></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Experiment 2: gradients are different from screenshots</h2><p className="mt-4">Choose the gradient pattern. This is a synthetic illustration with fine texture, not a photograph or a universal benchmark. Compare the sizes at 75% and 25% quality. Inspect the smooth transitions for bands and the tiny marks for smearing. The format with the fewest bytes is not automatically the version you should publish.</p><p className="mt-4">Next, choose an original photograph from your own device. Leaves, hair and fabric behave differently from this pattern. Keep the dimensions unchanged for your first comparison, so you can tell the effect of encoding apart from the effect of removing pixels. Results depend on the picture and your browser; there is no honest fixed saving percentage for every image.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Experiment 3: a logo on a transparent background</h2><p className="mt-4">Select the transparent graphic. The checkerboard represents empty pixels in the PNG and WebP previews. The JPG has a white background because JPEG cannot store transparency. Download the PNG and place it over a dark background to check the edges. For a header logo, a smaller white rectangle may be the wrong result even if it saves bytes.</p><Link className="text-orange-700 underline" href="/blog/resize-transparent-logo-png">Prepare a transparent logo</Link></section>
      <section><h2 className="text-2xl font-bold text-slate-950">What the numbers mean</h2><p className="mt-4">Every count comes from the newly encoded file. The PNG is a reference generated at the selected dimensions, not necessarily your original uploaded PNG. The comparison percentage is (PNG bytes − output bytes) ÷ PNG bytes × 100. A negative percentage means the output is larger. Halving both dimensions removes three quarters of the pixels, but does not guarantee a 75% reduction in bytes.</p><p className="mt-4">PNG is encoded without the JPG/WebP quality slider. A quality value of 75 does not mean 75% of the original visual quality, and values are not directly comparable across codecs. Browser encoders, fonts and source images affect the results. This lab makes no network request containing your selected file.</p><p className="mt-4">Browser exports can also change metadata and color handling. Keep camera originals and use a dedicated color-managed workflow for critical print work. For the underlying encoding behavior, see <a className="underline text-orange-700" href="https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob">the Canvas export documentation</a>.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Choose your next step</h2><ul className="mt-4 list-disc space-y-3 pl-5"><li>A portal gives a byte limit: use <Link className="underline text-orange-700" href="/resize-image-to-100kb">the 100 KB tool</Link>, then check pixel dimensions and readability separately.</li><li>The shape is wrong: <Link className="underline text-orange-700" href="/crop-image">crop the composition</Link> before resizing.</li><li>A website needs a narrower picture: <Link className="underline text-orange-700" href="/resize-image">resize by pixels</Link> with the aspect ratio locked.</li><li>The portal rejects the extension: <Link className="underline text-orange-700" href="/convert-image">convert the image</Link>; renaming the filename does not change its format.</li></ul></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Report a result that looks wrong</h2><p className="mt-4">Tell us the sample, dimensions, quality, browser and which result differs from your expectation. These settings make a report reproducible without sending a private document. <Link className="underline text-orange-700" href="/contact">Contact ResizeFox</Link>.</p></section>
    </div>
  </article></main>;
}
